const divisions=[
  {
    id:1,
    isPlayed:false,
    innerDiv:[
      {
        id:11,
        isPlayed:false,
        playedBy:0
      },
      {
        id:12,
        isPlayed:false,
        playedBy:0
      },
      {
        id:13,
        isPlayed:false,
        playedBy:0
      },
      {
        id:14,
        isPlayed:false,
        playedBy:0
      },
      {
        id:15,
        isPlayed:false,
        playedBy:0
      },
      {
        id:16,
        isPlayed:false,
        playedBy:0
      },
      {
        id:17,
        isPlayed:false,
        playedBy:0
      },
      {
        id:18,
        isPlayed:false,
        playedBy:0
      },
      {
        id:19,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:2,
    isPlayed:false,
    innerDiv:[
      {
        id:21,
        isPlayed:false,
        playedBy:0
      },
      {
        id:22,
        isPlayed:false,
        playedBy:0
      },
      {
        id:23,
        isPlayed:false,
        playedBy:0
      },
      {
        id:24,
        isPlayed:false,
        playedBy:0
      },
      {
        id:25,
        isPlayed:false,
        playedBy:0
      },
      {
        id:26,
        isPlayed:false,
        playedBy:0
      },
      {
        id:27,
        isPlayed:false,
        playedBy:0
      },
      {
        id:28,
        isPlayed:false,
        playedBy:0
      },
      {
        id:29,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:3,
    isPlayed:false,
    innerDiv:[
      {
        id:31,
        isPlayed:false,
        playedBy:0
      },
      {
        id:32,
        isPlayed:false,
        playedBy:0
      },
      {
        id:33,
        isPlayed:false,
        playedBy:0
      },
      {
        id:34,
        isPlayed:false,
        playedBy:0
      },
      {
        id:35,
        isPlayed:false,
        playedBy:0
      },
      {
        id:36,
        isPlayed:false,
        playedBy:0
      },
      {
        id:37,
        isPlayed:false,
        playedBy:0
      },
      {
        id:38,
        isPlayed:false,
        playedBy:0
      },
      {
        id:39,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:4,
    isPlayed:false,
    innerDiv:[
      {
        id:41,
        isPlayed:false,
        playedBy:0
      },
      {
        id:42,
        isPlayed:false,
        playedBy:0
      },
      {
        id:43,
        isPlayed:false,
        playedBy:0
      },
      {
        id:44,
        isPlayed:false,
        playedBy:0
      },
      {
        id:45,
        isPlayed:false,
        playedBy:0
      },
      {
        id:46,
        isPlayed:false,
        playedBy:0
      },
      {
        id:47,
        isPlayed:false,
        playedBy:0
      },
      {
        id:48,
        isPlayed:false,
        playedBy:0
      },
      {
        id:49,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:5,
    isPlayed:false,
    innerDiv:[
      {
        id:51,
        isPlayed:false,
        playedBy:0
      },
      {
        id:52,
        isPlayed:false,
        playedBy:0
      },
      {
        id:53,
        isPlayed:false,
        playedBy:0
      },
      {
        id:54,
        isPlayed:false,
        playedBy:0
      },
      {
        id:55,
        isPlayed:false,
        playedBy:0
      },
      {
        id:56,
        isPlayed:false,
        playedBy:0
      },
      {
        id:57,
        isPlayed:false,
        playedBy:0
      },
      {
        id:58,
        isPlayed:false,
        playedBy:0
      },
      {
        id:59,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:6,
    isPlayed:false,
    innerDiv:[
      {
        id:61,
        isPlayed:false,
        playedBy:0
      },
      {
        id:62,
        isPlayed:false,
        playedBy:0
      },
      {
        id:63,
        isPlayed:false,
        playedBy:0
      },
      {
        id:64,
        isPlayed:false,
        playedBy:0
      },
      {
        id:65,
        isPlayed:false,
        playedBy:0
      },
      {
        id:66,
        isPlayed:false,
        playedBy:0
      },
      {
        id:67,
        isPlayed:false,
        playedBy:0
      },
      {
        id:68,
        isPlayed:false,
        playedBy:0
      },
      {
        id:69,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:7,
    isPlayed:false,
    innerDiv:[
      {
        id:71,
        isPlayed:false,
        playedBy:0
      },
      {
        id:72,
        isPlayed:false,
        playedBy:0
      },
      {
        id:73,
        isPlayed:false,
        playedBy:0
      },
      {
        id:74,
        isPlayed:false,
        playedBy:0
      },
      {
        id:75,
        isPlayed:false,
        playedBy:0
      },
      {
        id:76,
        isPlayed:false,
        playedBy:0
      },
      {
        id:77,
        isPlayed:false,
        playedBy:0
      },
      {
        id:78,
        isPlayed:false,
        playedBy:0
      },
      {
        id:79,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:8,
    isPlayed:false,
    innerDiv:[
      {
        id:81,
        isPlayed:false,
        playedBy:0
      },
      {
        id:82,
        isPlayed:false,
        playedBy:0
      },
      {
        id:83,
        isPlayed:false,
        playedBy:0
      },
      {
        id:84,
        isPlayed:false,
        playedBy:0
      },
      {
        id:85,
        isPlayed:false,
        playedBy:0
      },
      {
        id:86,
        isPlayed:false,
        playedBy:0
      },
      {
        id:87,
        isPlayed:false,
        playedBy:0
      },
      {
        id:88,
        isPlayed:false,
        playedBy:0
      },
      {
        id:89,
        isPlayed:false,
        playedBy:0
      }
    ]
  },
  {
    id:9,
    isPlayed:false,
    innerDiv:[
      {
        id:91,
        isPlayed:false,
        playedBy:0
      },
      {
        id:92,
        isPlayed:false,
        playedBy:0
      },
      {
        id:93,
        isPlayed:false,
        playedBy:0
      },
      {
        id:94,
        isPlayed:false,
        playedBy:0
      },
      {
        id:95,
        isPlayed:false,
        playedBy:0
      },
      {
        id:96,
        isPlayed:false,
        playedBy:0
      },
      {
        id:97,
        isPlayed:false,
        playedBy:0
      },
      {
        id:98,
        isPlayed:false,
        playedBy:0
      },
      {
        id:99,
        isPlayed:false,
        playedBy:0
      }
    ]
  }
];

let gridDivHTML='';
let gridInnerDivHTML;

divisions.forEach((div)=>{
  gridInnerDivHTML='';
  div.innerDiv.forEach((innerdiv)=>{
    gridInnerDivHTML+=`<div class="inner-div-${innerdiv.id}"></div>`;
  });
  gridDivHTML+=`<div class="div-${div.id}">${gridInnerDivHTML}</div>`;
});

document.querySelector('.js-grid-div').innerHTML=gridDivHTML;

document.querySelector('.js-play-button').addEventListener('click',()=>{
  play();
});

function getRandomInt(max){
  return Math.floor(Math.random()*max);
}

let randomNum;
let randomNumIsUsed=false;
function play(){
  divisions.forEach((div)=>{
    div.innerDiv.forEach((innerdiv)=>{
      do{
        randomNum=getRandomInt(10);
        div.innerDiv.forEach((inrdiv)=>{
          if(randomNum===0){
            randomNumIsUsed=false;
          }else if(randomNum===inrdiv.playedBy){
            randomNumIsUsed=true;
          }
        });
        for(let i=1;i<=i+6;i+=3){
          for(let j=1;j<=j+6;j+=3){
            div.innerDiv.forEach((inrdiv)=>{
              if(inrdiv.id===(i*10)+j && randomNum===inrdiv.playedBy){
                
              }
            });
          }
        }
      }while(randomNumIsUsed);
      innerdiv.isPlayed=true;
      innerdiv.playedBy=randomNum;
      if(randomNum===0){
        document.querySelector(`.inner-div-${innerdiv.id}`).innerHTML='';
      }else{
        document.querySelector(`.inner-div-${innerdiv.id}`).innerHTML=innerdiv.playedBy;
      }
    });
    
  });
}

